baseURL = "https://gaozl9515.github.io/qingshui.github.io/"
languageCode = 'en-us'
title = '我的 Hugo 站点'

[module]
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = false
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false
